language: cpp
compiler:
    - gcc
    - clang
dist: xenial
python:
  - "3.7"
addons:
    apt:
        packages:
            - python
            - python-pip
            - python-setuptools

before_install:
    - python --version
    - pip install -U pip
    - pip install -U setuptools
    - pip install -U online-judge-tools=='7.2.*'
script:
    - ./test/test.sh
