name: sanitize

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/kmyk/online-judge-verify-helper.git@master

    - name: Run tests
      env:
        CXXFLAGS: "-fsanitize=undefined -D_GLIBCXX_DEBUG"
      run: env -u GITHUB_ACTION oj-verify run -j 2
