name: sanitize

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U https://github.com/beet-aizu/online-judge-verify-helper.git@add_tle_options

    - name: Run tests
      env:
        CXXFLAGS: "-fsanitize=undefined -D_GLIBCXX_DEBUG"
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify run -j 2 --timeout 3600 --tle 600
